---
title: "ABV rapporten"
output: 
  html_document:
    css: 
      - !expr system.file(file.path("css_styles", "inbo_report.css"), package = "INBOmd")
      - extra.css
---

ABV staat voor de Algemene Broedvogelmonitoring Vlaanderen.
Dit project is een gezamenlijk initiatief van het Instituut voor Natuur- en Bosonderzoek (INBO) en Natuurpunt Studie in samenwerking met de lokale vogelwerkgroepen. 
De samenwerking tussen deze organisaties staat garant voor een goede ondersteuning van en communicatie naar het vrijwilligersnetwerk door Natuurpunt Studie, en een degelijke professionele wetenschappelijke ondersteuning en dataverwerking door het INBO.

Het project werd opgestart in 2007 en heeft als doelstelling het beschrijven van aantalsontwikkelingen van een set van ca. 80 algemene broedvogelsoorten in Vlaanderen. 
Zowel jaarlijkse fluctuaties als meerjarige trends zijn daarbij interessante resultaten in functie van lokaal, regionaal en/of internationaal beleid.

Dit rapport is bedoeld als een technisch achtergrondrapport.
Het bestaat uit drie delen: 
het eerste deel beschrijft de methodiek van de verwerking en de weergave van de resultaten;
het tweede deel geeft een aantal indicatoren gebaseerd op trends van meerdere soorten;
het derde deel beschrijft de tijdreeks van individuele soorten.
We beperken ons in delen twee en drie tot een droge, gestandaardiseerde weergave van de cijfers zonder ecologische interpretatie.
Voor een ecologische interpretatie van de resultaten verwijzen we naar andere publicaties zoals [INBO Vogelnieuws](https://pureportal.inbo.be/portal/nl/publications/search.html?lastName=&search=&organisationName=&publicationYearsFrom=&organisations=&advanced=true&documents=%20&language=%20&publicationYearsTo=&type=%2Fdk%2Fatira%2Fpure%2Fresearchoutput%2Fresearchoutputtypes%2Fcontributiontojournal%2Finbovogelnieuws&uri=&logicalname=%2Fdk%2Fatira%2Fpure%2Fthematic&ordering=researchOutputOrderByPublicationYear&descending=true).

# Beschikbare rapporten

| periode | [DOI](https://nl.wikipedia.org/wiki/Digital_object_identifier) | interactief | pdf | [E-boek](https://nl.wikipedia.org/wiki/E-boek) |
| - | - | - | - | - |
| 2007 - 2018 | [10.5281/zenodo.1494832](https://doi.org/10.5281/zenodo.1494832) | | [pdf](2018/abv.pdf) | |
| 2007 - 2019 | [10.21436/inbor.17888433](https://doi.org/10.21436/inbor.17888433) | [html](2019/index.html) | [pdf](2019/abv_standaard_rapport.pdf) | [epub](2019/abv_standaard_rapport.epub) |
| 2007 - 2020 | [10.21436/inbor.34162521](https://doi.org/10.21436/inbor.34162521) | [html](2020/index.html) | [pdf](2020/abv_standaard_rapport.pdf) | |
| 2007 - 2021 | [10.21436/inbor.73009782](https://doi.org/10.21436/inbor.73009782) | [html](2021/index.html) | [pdf](2021/abv_standaard_rapport.pdf) | [epub](2021/abv_standaard_rapport.epub) |
